server:
  port: 9200

temporary-file-path: ${java.io.tmpdir}
static-file-context:

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://glovv-db-instance-primary.cynaafs4po9d.ap-northeast-2.rds.amazonaws.com:3306/bestlc
    username: glovv_dba
    password: CC1q2w3e4r!!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 4
      idle-timeout: 10000
      max-lifetime: 420000
      validation-timeout: 10000
      pool-name: primaryPool
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  redis:
    host: localhost
    port: 6379
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
